"""Fixed relation2

Revision ID: ff75a3612634
Revises: 54e27ffea94d
Create Date: 2026-04-13 14:38:43.456699

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ff75a3612634'
down_revision: Union[str, None] = '54e27ffea94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
