"""Fixed relation for training

Revision ID: a5dc6520856b
Revises: ff75a3612634
Create Date: 2026-04-13 21:40:37.919026

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a5dc6520856b'
down_revision: Union[str, None] = 'ff75a3612634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('customer_feature_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predictions', 'customer_features', ['customer_feature_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'customer_feature_id')
    # ### end Alembic commands ###
