"""add feature tabel and training pipline tables

Revision ID: 1b2eef8b8264
Revises: 807fa1ed4ab0
Create Date: 2026-04-13 14:32:01.469030

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1b2eef8b8264'
down_revision: Union[str, None] = '807fa1ed4ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
