"""Fixed inference input

Revision ID: 807fa1ed4ab0
Revises: e10e49dd4e6a
Create Date: 2026-04-13 14:15:46.211198

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '807fa1ed4ab0'
down_revision: Union[str, None] = 'e10e49dd4e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
