"""add feature tabel and training pipline tables

Revision ID: 75a1a48c822d
Revises: 62d755e8478e
Create Date: 2026-04-13 13:40:51.341352

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '75a1a48c822d'
down_revision: Union[str, None] = '62d755e8478e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('train_size', sa.Integer(), nullable=False),
    sa.Column('test_size', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('balanced_accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('roc_auc', sa.Float(), nullable=False),
    sa.Column('pr_auc', sa.Float(), nullable=False),
    sa.Column('mcc', sa.Float(), nullable=False),
    sa.Column('true_negatives', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('false_negatives', sa.Integer(), nullable=False),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('education', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('kidhome', sa.Integer(), nullable=False),
    sa.Column('teenhome', sa.Integer(), nullable=False),
    sa.Column('recency', sa.Integer(), nullable=False),
    sa.Column('num_store_purchases', sa.Integer(), nullable=False),
    sa.Column('response', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('customer_tenure_days', sa.Integer(), nullable=False),
    sa.Column('mnt_wines_log', sa.Float(), nullable=False),
    sa.Column('mnt_meat_products_log', sa.Float(), nullable=False),
    sa.Column('mnt_fruits_log', sa.Float(), nullable=False),
    sa.Column('mnt_fish_products_log', sa.Float(), nullable=False),
    sa.Column('mnt_sweet_products_log', sa.Float(), nullable=False),
    sa.Column('mnt_gold_prods_log', sa.Float(), nullable=False),
    sa.Column('num_catalog_purchases_log', sa.Float(), nullable=False),
    sa.Column('num_web_purchases_log', sa.Float(), nullable=False),
    sa.Column('total_mnt', sa.Float(), nullable=False),
    sa.Column('total_purchases', sa.Integer(), nullable=False),
    sa.Column('wine_ratio', sa.Float(), nullable=False),
    sa.Column('meat_ratio', sa.Float(), nullable=False),
    sa.Column('premium_ratio', sa.Float(), nullable=False),
    sa.Column('catalog_share', sa.Float(), nullable=False),
    sa.Column('is_alone', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_feature_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('prediction_proba', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_feature_id'], ['customer_features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.alter_column('customers', 'income',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Annual household income',
               existing_nullable=True)
    op.alter_column('customers', 'kidhome',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of small children',
               existing_nullable=False)
    op.alter_column('customers', 'teenhome',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of teenagers',
               existing_nullable=False)
    op.alter_column('customers', 'dt_customer',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Customer registration date',
               existing_nullable=True)
    op.alter_column('customers', 'num_deals_purchases',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Purchases with discount',
               existing_nullable=False)
    op.alter_column('customers', 'num_web_purchases',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Purchases through website',
               existing_nullable=False)
    op.alter_column('customers', 'num_catalog_purchases',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Purchases through catalog',
               existing_nullable=False)
    op.alter_column('customers', 'num_store_purchases',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Purchases in store',
               existing_nullable=False)
    op.alter_column('customers', 'num_web_visits_month',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Website visits per month',
               existing_nullable=False)
    op.alter_column('customers', 'recency',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Days since last purchase',
               existing_nullable=False)
    op.alter_column('customers', 'complain',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Complaint in the last 2 years',
               existing_nullable=False)
    op.alter_column('customers', 'response',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Accepted gold membership offer',
               existing_nullable=False)
    op.alter_column('customers', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Randomly generated timestamp within 2025',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='Randomly generated timestamp within 2025',
               existing_nullable=False)
    op.alter_column('customers', 'response',
               existing_type=sa.BOOLEAN(),
               comment='Accepted gold membership offer',
               existing_nullable=False)
    op.alter_column('customers', 'complain',
               existing_type=sa.BOOLEAN(),
               comment='Complaint in the last 2 years',
               existing_nullable=False)
    op.alter_column('customers', 'recency',
               existing_type=sa.INTEGER(),
               comment='Days since last purchase',
               existing_nullable=False)
    op.alter_column('customers', 'num_web_visits_month',
               existing_type=sa.INTEGER(),
               comment='Website visits per month',
               existing_nullable=False)
    op.alter_column('customers', 'num_store_purchases',
               existing_type=sa.INTEGER(),
               comment='Purchases in store',
               existing_nullable=False)
    op.alter_column('customers', 'num_catalog_purchases',
               existing_type=sa.INTEGER(),
               comment='Purchases through catalog',
               existing_nullable=False)
    op.alter_column('customers', 'num_web_purchases',
               existing_type=sa.INTEGER(),
               comment='Purchases through website',
               existing_nullable=False)
    op.alter_column('customers', 'num_deals_purchases',
               existing_type=sa.INTEGER(),
               comment='Purchases with discount',
               existing_nullable=False)
    op.alter_column('customers', 'dt_customer',
               existing_type=sa.DATE(),
               comment='Customer registration date',
               existing_nullable=True)
    op.alter_column('customers', 'teenhome',
               existing_type=sa.INTEGER(),
               comment='Number of teenagers',
               existing_nullable=False)
    op.alter_column('customers', 'kidhome',
               existing_type=sa.INTEGER(),
               comment='Number of small children',
               existing_nullable=False)
    op.alter_column('customers', 'income',
               existing_type=sa.INTEGER(),
               comment='Annual household income',
               existing_nullable=True)
    op.drop_table('inference_inputs')
    op.drop_table('predictions')
    op.drop_table('customer_features')
    op.drop_table('training_results')
    # ### end Alembic commands ###
