"""change income type to integer

Revision ID: 62d755e8478e
Revises: d5f3784fe355
Create Date: 2026-03-03 15:00:34.430374

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '62d755e8478e'
down_revision: Union[str, None] = 'd5f3784fe355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'income',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_comment='Annual household income',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'income',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_comment='Annual household income',
               existing_nullable=True)
    # ### end Alembic commands ###
