"""Fixed relation

Revision ID: 54e27ffea94d
Revises: 1b2eef8b8264
Create Date: 2026-04-13 14:36:40.398422

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '54e27ffea94d'
down_revision: Union[str, None] = '1b2eef8b8264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('predictions_customer_feature_id_fkey', 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'customer_feature_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('customer_feature_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('predictions_customer_feature_id_fkey', 'predictions', 'customer_features', ['customer_feature_id'], ['id'])
    # ### end Alembic commands ###
