"""Fixed inference input

Revision ID: 0d73041b875d
Revises: 75a1a48c822d
Create Date: 2026-04-13 13:52:21.886136

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0d73041b875d'
down_revision: Union[str, None] = '75a1a48c822d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_inputs', sa.Column('year_birth', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('education', sa.String(length=50), nullable=False))
    op.add_column('inference_inputs', sa.Column('marital_status', sa.String(length=50), nullable=False))
    op.add_column('inference_inputs', sa.Column('income', sa.Float(), nullable=False))
    op.add_column('inference_inputs', sa.Column('kidhome', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('teenhome', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('dt_customer', sa.String(length=20), nullable=False))
    op.add_column('inference_inputs', sa.Column('recency', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('mnt_wines', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('mnt_fruits', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('mnt_meat_products', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('mnt_fish_products', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('mnt_sweet_products', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('mnt_gold_prods', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('num_deals_purchases', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('num_web_purchases', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('num_catalog_purchases', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('num_store_purchases', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('num_web_visits_month', sa.Integer(), nullable=False))
    op.add_column('inference_inputs', sa.Column('complain', sa.Integer(), nullable=False))
    op.drop_column('inference_inputs', 'input_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_inputs', sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('inference_inputs', 'complain')
    op.drop_column('inference_inputs', 'num_web_visits_month')
    op.drop_column('inference_inputs', 'num_store_purchases')
    op.drop_column('inference_inputs', 'num_catalog_purchases')
    op.drop_column('inference_inputs', 'num_web_purchases')
    op.drop_column('inference_inputs', 'num_deals_purchases')
    op.drop_column('inference_inputs', 'mnt_gold_prods')
    op.drop_column('inference_inputs', 'mnt_sweet_products')
    op.drop_column('inference_inputs', 'mnt_fish_products')
    op.drop_column('inference_inputs', 'mnt_meat_products')
    op.drop_column('inference_inputs', 'mnt_fruits')
    op.drop_column('inference_inputs', 'mnt_wines')
    op.drop_column('inference_inputs', 'recency')
    op.drop_column('inference_inputs', 'dt_customer')
    op.drop_column('inference_inputs', 'teenhome')
    op.drop_column('inference_inputs', 'kidhome')
    op.drop_column('inference_inputs', 'income')
    op.drop_column('inference_inputs', 'marital_status')
    op.drop_column('inference_inputs', 'education')
    op.drop_column('inference_inputs', 'year_birth')
    # ### end Alembic commands ###
