"""update inference input cols

Revision ID: e10e49dd4e6a
Revises: 0d73041b875d
Create Date: 2026-04-13 14:13:41.143867

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e10e49dd4e6a'
down_revision: Union[str, None] = '0d73041b875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education_levels', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education_levels', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('education_levels_id_seq'::regclass)"),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
