"""initial schema

Revision ID: d5f3784fe355
Revises: 
Create Date: 2026-03-03 14:34:12.880646

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd5f3784fe355'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marital_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('year_birth', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=12, scale=2), nullable=True, comment='Annual household income'),
    sa.Column('kidhome', sa.Integer(), nullable=False, comment='Number of small children'),
    sa.Column('teenhome', sa.Integer(), nullable=False, comment='Number of teenagers'),
    sa.Column('dt_customer', sa.Date(), nullable=True, comment='Customer registration date'),
    sa.Column('education_level_id', sa.Integer(), nullable=True),
    sa.Column('marital_status_id', sa.Integer(), nullable=True),
    sa.Column('mnt_wines', sa.Integer(), nullable=False),
    sa.Column('mnt_fruits', sa.Integer(), nullable=False),
    sa.Column('mnt_meat_products', sa.Integer(), nullable=False),
    sa.Column('mnt_fish_products', sa.Integer(), nullable=False),
    sa.Column('mnt_sweet_products', sa.Integer(), nullable=False),
    sa.Column('mnt_gold_prods', sa.Integer(), nullable=False),
    sa.Column('num_deals_purchases', sa.Integer(), nullable=False, comment='Purchases with discount'),
    sa.Column('num_web_purchases', sa.Integer(), nullable=False, comment='Purchases through website'),
    sa.Column('num_catalog_purchases', sa.Integer(), nullable=False, comment='Purchases through catalog'),
    sa.Column('num_store_purchases', sa.Integer(), nullable=False, comment='Purchases in store'),
    sa.Column('num_web_visits_month', sa.Integer(), nullable=False, comment='Website visits per month'),
    sa.Column('recency', sa.Integer(), nullable=False, comment='Days since last purchase'),
    sa.Column('complain', sa.Boolean(), nullable=False, comment='Complaint in the last 2 years'),
    sa.Column('response', sa.Boolean(), nullable=False, comment='Accepted gold membership offer'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Randomly generated timestamp within 2025'),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ),
    sa.ForeignKeyConstraint(['marital_status_id'], ['marital_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('marital_statuses')
    op.drop_table('education_levels')
    # ### end Alembic commands ###
