"""Added true label

Revision ID: 518726da4679
Revises: a5dc6520856b
Create Date: 2026-04-13 23:43:00.772102

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '518726da4679'
down_revision: Union[str, None] = 'a5dc6520856b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('true_label', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'true_label')
    # ### end Alembic commands ###
